Repository github/branch-deploy, pull requests merged in 2023-03, with the labels that each got.

#105 fix draft pr bug
  __tests__/functions/prechecks.test.js
  dist/index.js
  dist/index.js.map
  src/functions/prechecks.js
Labels: bug

#106 Add Additional Outputs
  README.md
  __tests__/main.test.js
  action.yml
  dist/index.js
  dist/index.js.map
  src/main.js
Labels: enhancement

#111 GHES Support
  dist/index.js
  dist/index.js.map
  src/functions/deployment.js
  src/functions/lock.js
  src/main.js
Labels: enhancement

#112 Server URL Fixes
  dist/index.js
  dist/index.js.map
  src/functions/deployment.js
  src/functions/lock.js
  src/main.js
Labels: bug

#114 Add `sha` to outputs
  README.md
  __tests__/main.test.js
  action.yml
  dist/index.js
  dist/index.js.map
  src/main.js
Labels: enhancement

#116 Add `sha` to Action outputs
  README.md
  __tests__/functions/prechecks.test.js
  __tests__/main.test.js
  action.yml
  dist/index.js
  dist/index.js.map
  src/functions/prechecks.js
  src/main.js
Labels: enhancement

#121 Add auto_merge option for GitHub create a deployment API
  dist/index.js
  dist/index.js.map
  src/main.js
Labels: bug

#120 Environment Specific Locks 🌍 🔒
  README.md
  __tests__/functions/environment-targets.test.js
  __tests__/functions/help.test.js
  __tests__/functions/lock.test.js
  __tests__/functions/post-deploy.test.js
  __tests__/functions/unlock.test.js
  __tests__/main.test.js
  action.yml
  dist/index.js
  dist/index.js.map
  docs/custom-deployment-messages.md
  docs/locks.md
  docs/merge-commit-strategy.md
  docs/usage.md
  package-lock.json
  package.json
  script/release
  src/functions/environment-targets.js
  src/functions/help.js
  src/functions/lock-metadata.js
  src/functions/lock.js
  src/functions/post-deploy.js
  src/functions/unlock.js
  src/main.js
Labels: enhancement

#123 Lock Link Fixes
  dist/index.js
  dist/index.js.map
  src/functions/lock.js
  src/main.js
Labels: bug

#124 HAS_HOOKS checks
  __tests__/functions/prechecks.test.js
  dist/index.js
  dist/index.js.map
  src/functions/prechecks.js
Labels: bug

#128 `environment_url` in deployments
  README.md
  __tests__/functions/deployment.test.js
  __tests__/functions/environment-targets.test.js
  __tests__/functions/post-deploy.test.js
  __tests__/main.test.js
  action.yml
  dist/index.js
  dist/index.js.map
  src/functions/deployment.js
  src/functions/environment-targets.js
  src/functions/post-deploy.js
  src/functions/post.js
  src/main.js
Labels: enhancement

#130 --reason (lock/unlock) bug fixes
  __tests__/functions/environment-targets.test.js
  __tests__/functions/post.test.js
  dist/index.js
  dist/index.js.map
  src/functions/environment-targets.js
  src/functions/post.js
Labels: bug

#131 ensure --reason is removed from unlock commands
  __tests__/functions/unlock.test.js
  dist/index.js
  dist/index.js.map
  src/functions/unlock.js
Labels: bug

#134 Examples Docs Updates
  .github/workflows/package-check.yml
  docs/examples.md
Labels: documentation

#135 Update all Actions Workflows
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yml
  .github/workflows/package-check.yml
  .github/workflows/test.yml
Labels: dependencies, github_actions

#136 More docs updates
  README.md
  docs/examples.md
Labels: documentation

#138 General Repo Updates
  .github/CODEOWNERS
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yml
  .github/workflows/package-check.yml
  .github/workflows/test.yml
  .gitignore
  dist/index.js
  dist/index.js.map
  package-lock.json
  package.json
Labels: dependencies, github_actions

#139 Action Config Validation
  .github/workflows/actions-config-validation.yml
  README.md
  __tests__/schemas/action.schema.yml
Labels: github_actions

#140 Upgrade yaml validation
  .github/config/exclude.txt
  .github/workflows/actions-config-validation.yml
Labels: dependencies, github_actions
