Repository github/branch-deploy, pull requests merged in 2023-06, with the labels that each got.

#146 Parameter Support
  README.md
  __tests__/functions/environment-targets.test.js
  __tests__/functions/help.test.js
  __tests__/functions/prechecks.test.js
  __tests__/functions/trigger-check.test.js
  __tests__/main.test.js
  __tests__/schemas/action.schema.yml
  action.yml
  dist/index.js
  dist/index.js.map
  docs/parameters.md
  src/functions/environment-targets.js
  src/functions/help.js
  src/functions/trigger-check.js
  src/main.js
Labels: bug, enhancement

#149 Package Updates
  .gitattributes
  .github/ISSUE_TEMPLATE/question.yml
  .github/workflows/actions-config-validation.yml
  .github/workflows/package-check.yml
  .gitignore
  package-lock.json
Labels: dependencies

#150 Auto Release Deployment Locks
  README.md
  __tests__/functions/unlock-on-merge.test.js
  __tests__/functions/unlock.test.js
  __tests__/main.test.js
  __tests__/schemas/action.schema.yml
  action.yml
  dist/index.js
  dist/index.js.map
  docs/merge-commit-strategy.md
  docs/unlock-on-merge.md
  src/functions/unlock-on-merge.js
  src/functions/unlock.js
  src/main.js
Labels: enhancement

#151 Unlock on merge fixes
  __tests__/functions/unlock-on-merge.test.js
  dist/index.js
  dist/index.js.map
  src/functions/check-lock-file.js
  src/functions/lock.js
  src/functions/unlock-on-merge.js
  src/main.js
Labels: bug

#152 update docs
  docs/unlock-on-merge.md
Labels: documentation

#153 update 'Unlock On Merge Mode' docs
  docs/unlock-on-merge.md
Labels: documentation

#157 Added 'maintain' role to valid-permissions.js
  __tests__/functions/prechecks.test.js
  dist/index.js
  dist/index.js.map
  src/functions/valid-permissions.js
Labels: bug, enhancement

#161 v6.0.0 Improvements
  README.md
  __tests__/functions/help.test.js
  __tests__/functions/prechecks.test.js
  __tests__/functions/trigger-check.test.js
  __tests__/functions/valid-permissions.test.js
  __tests__/schemas/action.schema.yml
  action.yml
  dist/index.js
  dist/index.js.map
  src/functions/help.js
  src/functions/trigger-check.js
  src/functions/valid-permissions.js
  src/main.js
Labels: enhancement

#162 update unlock-on-merge docs
  docs/unlock-on-merge.md
Labels: documentation

#164 node package updates
  dist/index.js
  dist/index.js.map
  package-lock.json
Labels: dependencies
