Repository github/branch-deploy, pull requests merged in 2023-09, with the labels that each got.

#194 add base_ref output
  README.md
  __tests__/functions/prechecks.test.js
  __tests__/schemas/action.schema.yml
  action.yml
  dist/index.js
  dist/index.js.map
  src/functions/prechecks.js
Labels: enhancement

#197 update docs
  README.md
  __tests__/schemas/action.schema.yml
  action.yml
Labels: documentation

#199 Hubot Style Deploy Locking :lock:
  README.md
  __tests__/functions/unlock-on-merge.test.js
  __tests__/main.test.js
  __tests__/schemas/action.schema.yml
  action.yml
  dist/index.js
  dist/index.js.map
  src/functions/lock.js
  src/functions/post-deploy.js
  src/functions/unlock-on-merge.js
  src/main.js
Labels: enhancement

#200 Update docs
  README.md
  docs/hubot-style-deployment-locks.md
Labels: documentation

#202 Sticky Locks for `noop` deployments
  README.md
  __tests__/main.test.js
  __tests__/schemas/action.schema.yml
  action.yml
  dist/index.js
  dist/index.js.map
  docs/hubot-style-deployment-locks.md
  src/main.js
Labels: enhancement

#204 Simplify identical commit check using tree SHAs.
  src/functions/identical-commit-check.js
Labels: bug, enhancement

#205 Identical commit check fixes
  __tests__/functions/identical-commit-check.test.js
  dist/index.js
  dist/index.js.map
  src/functions/identical-commit-check.js
Labels: enhancement

#207 update all node dependencies
  dist/index.js
  dist/index.js.map
  package-lock.json
Labels: dependencies

#209 Support Multiple Production Environments
  README.md
  __tests__/functions/help.test.js
  __tests__/main.test.js
  __tests__/schemas/action.schema.yml
  action.yml
  dist/index.js
  dist/index.js.map
  src/functions/help.js
  src/main.js
Labels: enhancement
