Repository github/branch-deploy, pull requests merged in 2023-02, with the labels that each got.

#84 Merge commit comparison
  README.md
  __tests__/functions/identical-commit-check.test.js
  __tests__/main.test.js
  action.yml
  dist/index.js
  dist/index.js.map
  src/functions/identical-commit-check.js
  src/main.js
Labels: enhancement

#85 use compareCommitsWithBasehead and rest.<api>
  __tests__/functions/identical-commit-check.test.js
  dist/index.js
  dist/index.js.map
  src/functions/identical-commit-check.js
Labels: bug

#86 Change post
  dist/index.js
  dist/index.js.map
  src/main.js
Labels: bug

#90 Merge commit sha fixes
  __tests__/functions/identical-commit-check.test.js
  dist/index.js
  dist/index.js.map
  package-lock.json
  package.json
  src/functions/identical-commit-check.js
Labels: bug

#96 Environment Bypasses for Checks and Reviews
  README.md
  __tests__/functions/prechecks.test.js
  __tests__/functions/string-to-array.test.js
  action.yml
  dist/index.js
  dist/index.js.map
  src/functions/prechecks.js
  src/functions/string-to-array.js
  src/main.js
Labels: enhancement

#97 Blocked Merge State - Bug
  __tests__/functions/prechecks.test.js
  dist/index.js
  dist/index.js.map
  src/functions/prechecks.js
Labels: bug

#98 Help Command
  README.md
  __tests__/functions/help.test.js
  __tests__/main.test.js
  action.yml
  dist/index.js
  dist/index.js.map
  src/functions/help.js
  src/main.js
Labels: enhancement

#103 Add `skip_completing` option
  __tests__/functions/post.test.js
  action.yml
  dist/index.js
  dist/index.js.map
  docs/examples.md
  src/functions/post.js
Labels: enhancement

#104 update docs
  README.md
  action.yml
Labels: documentation
