Repository github/branch-deploy, pull requests merged in 2024-06, with the labels that each got.

#266 handle messages that are bigger than issue body limit
  __tests__/functions/actions-status.test.js
  __tests__/functions/truncate-comment-body.test.js
  dist/index.js
  dist/index.js.map
  src/functions/action-status.js
  src/functions/truncate-comment-body.js
Labels: bug, enhancement

#268 update all internal node packages
  dist/index.js
  dist/index.js.map
  package-lock.json
Labels: dependencies

#270 Truncate improvements
  __tests__/functions/actions-status.test.js
  __tests__/functions/truncate-comment-body.test.js
  dist/index.js
  dist/index.js.map
  src/functions/truncate-comment-body.js
Labels: enhancement

#272 Post Deploy Feature Improvements
  README.md
  __tests__/functions/check-input.test.js
  __tests__/functions/label.test.js
  __tests__/functions/post-deploy-message.test.js
  __tests__/functions/post-deploy.test.js
  __tests__/functions/post.test.js
  __tests__/functions/prechecks.test.js
  __tests__/functions/string-to-array.test.js
  __tests__/schemas/action.schema.yml
  __tests__/templates/test_deployment_message.md
  action.yml
  dist/index.js
  dist/index.js.map
  docs/custom-deployment-messages.md
  src/functions/check-input.js
  src/functions/environment-targets.js
  src/functions/label.js
  src/functions/post-deploy-message.js
  src/functions/post-deploy.js
  src/functions/post.js
  src/functions/prechecks.js
  src/functions/string-to-array.js
  src/functions/valid-permissions.js
  src/main.js
Labels: enhancement

#273 node package updates
  package-lock.json
Labels: dependencies
