Repository github/branch-deploy, pull requests merged in 2024-02, with the labels that each got.

#237 Update Base Branch Improvements
  README.md
  __tests__/functions/help.test.js
  __tests__/functions/outdated-check.test.js
  __tests__/functions/prechecks.test.js
  __tests__/schemas/action.schema.yml
  action.yml
  dist/index.js
  dist/index.js.map
  docs/outdated_mode.md
  src/functions/help.js
  src/functions/outdated-check.js
  src/functions/prechecks.js
  src/main.js
Labels: enhancement

#240 update all node deps
  dist/index.js
  dist/index.js.map
  package-lock.json
Labels: dependencies

#241 Add checks mode input
  __tests__/functions/prechecks.test.js
  __tests__/schemas/action.schema.yml
  action.yml
  dist/index.js
  dist/index.js.map
  src/functions/prechecks.js
  src/main.js
Labels: enhancement

#243 node package updates
  dist/index.js
  dist/index.js.map
  package-lock.json
Labels: dependencies

#244 Checks input docs
  README.md
  __tests__/functions/help.test.js
  action.yml
  dist/index.js
  dist/index.js.map
  docs/assets/required-ci-checks-example.png
  docs/assets/required-ci-checks.png
  docs/checks.md
  src/functions/help.js
Labels: documentation
